public class InvalidCardException extends Exception {

	/**
	 * Autogenerated serialVersionUID
	 */
	private static final long serialVersionUID = 2006919217943530036L;

	public InvalidCardException() {
	}

	public InvalidCardException(String message) {
		super(message);
	}

	public InvalidCardException(Throwable cause) {
		super(cause);
	}

	public InvalidCardException(String message, Throwable cause) {
		super(message, cause);
	}
}
